# Generated by Django 2.2.28 on 2022-12-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikeshare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start_time')),
                ('end_time', models.DateTimeField(verbose_name='end_time')),
                ('tripduration', models.IntegerField(verbose_name='tripduration')),
                ('from_station_id', models.CharField(max_length=10, verbose_name='from_station_id')),
                ('from_station_name', models.CharField(max_length=255, verbose_name='from_station_name')),
                ('to_station_id', models.CharField(max_length=10, verbose_name='to_station_id')),
                ('to_station_name', models.CharField(max_length=255, verbose_name='to_station_name')),
                ('usertype', models.CharField(max_length=50, verbose_name='usertype')),
                ('from_Latitude', models.FloatField(verbose_name='from_Latitude')),
                ('from_Longitude', models.FloatField(verbose_name='from_Longitude')),
                ('from_Location', models.CharField(max_length=150, verbose_name='from_Location')),
                ('to_Latitude', models.FloatField(verbose_name='to_Latitude')),
                ('to_Longitude', models.FloatField(verbose_name='to_Longitude')),
                ('to_Location', models.CharField(max_length=150, verbose_name='to_Location')),
            ],
        ),
    ]
